paypal:
  client-id: Af9cJjOR3dzGYtgxGG07SP7-Rdgan4TCbxKc41R4_gis6wOU_t7lyzMtlwpnwyOS1FC5ucIOtu_5RTEE
  client-secret: Af9cJjOR3dzGYtgxGG07SP7-Rdgan4TCbxKc41R4_gis6wOU_t7lyzMtlwpnwyOS1FC5ucIOtu_5RTEE
  mode: sandbox #sandbox for test and live for production
